//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosproject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class category
    {
        public category()
        {
            this.foods = new HashSet<food>();
        }
    
        public int categoryid { get; set; }
        [Required]
        [Display(Name="Tên chuyên mục")]
        public string categoryname { get; set; }
        [Required]
        [Display(Name = "Trạng thái")]
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<food> foods { get; set; }
    }
}
