//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosproject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class food
    {
        public food()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
       
        [Display(Name = "ID món ăn")]
        public int foodid { get; set; }
        [Required]
          [Display(Name = "ID chuyên mục")]
        public int categoryid { get; set; }
        [Required]
        [Display(Name = "Tên món ăn")]
        public string foodname { get; set; }
        [Required]
        [Display(Name = "Giá món ăn")]
        public double price { get; set; }
        [Required]
        [Display(Name = "Trạng thái món ăn")]
        public Nullable<bool> status { get; set; }
        [Required]
        [Display(Name = "Nội dung món ăn")]
        public string contents { get; set; }
        [DataType(DataType.Upload)]
        [Display(Name = "Ảnh món ăn")]     
        public string foodimage { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
