//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int orderid { get; set; }
        public int foodid { get; set; }
        public Nullable<int> daubepid { get; set; }
        public int quantity { get; set; }
        public double unitcost { get; set; }
        public string comment { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual food food { get; set; }
        public virtual order order { get; set; }
    }
}
