//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int orderid { get; set; }
        public int userid { get; set; }
        public int tableid { get; set; }
        public System.DateTime orderdate { get; set; }
        public Nullable<bool> status { get; set; }
        public int customerid { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual table table { get; set; }
        public virtual user user { get; set; }
    }
}
