//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class table
    {
        public table()
        {
            this.orders = new HashSet<order>();
        }
    
        public int tableid { get; set; }
        public string tablename { get; set; }
        public Nullable<bool> status { get; set; }
        public int seatnums { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
    }
}
