//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosproject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        public user()
        {
            this.orders = new HashSet<order>();
        }
        [Display(Name="ID người dùng")]
        public int userid { get; set; }
        [Required]
        [Display(Name = "Tên người dùng")]
        public string username { get; set; }
          [Required]
        [Display(Name = "Mật khẩu người dùng")]
        public string password { get; set; }
        [Required]
        [Display(Name = "Tên đầy đủ người dùng")]
        public string fullname { get; set; }
        [Required]
        [Display(Name = "Trạng thái người dùng")]
        public Nullable<bool> status { get; set; }
        [Required]
        [Display(Name = "Quyền hạn người dùng")]
        public int permission { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
    }
}
